[build.processing]
skip_processing = false
[build.processing.css]
bundle = true
minify = true
[build.processing.js]
bundle = true
minify = true
[build.processing.html]
pretty_urls = true
[build.processing.images]
compress = true

[[redirects]]
from = "/*"
to = "https://routing-algorithms.netlify.app/"
status = 200
force = true
headers = { X-From = "Netlify" }
